# Generated by Django 2.2.20 on 2021-04-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0058_remove_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title', 'upc']},
        ),
    ]
